name: OpenSearch Plugin Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opensearch-version: ['2.15.0', '2.17.0']  # Test multiple versions
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build plugin
        run: |
          ./gradlew build

      - name: Start OpenSearch container
        run: |
          docker run -d \
            -p 9200:9200 -p 9600:9600 \
            -e "discovery.type=single-node" \
            -e "plugins.security.disabled=true" \
            --name opensearch \
            opensearchproject/opensearch:${{ matrix.opensearch-version }}
          
          # Wait for OpenSearch to start up
          echo "Waiting for OpenSearch to start..."
          timeout 120 bash -c 'until curl -s -f http://localhost:9200/_cluster/health?wait_for_status=yellow; do sleep 2; done'

      - name: Install plugin
        run: |
          # Copy and install plugin
          docker cp build/distributions/opensearch-late-interaction-1.0.0.0.zip opensearch:/tmp/
          docker exec opensearch /usr/share/opensearch/bin/opensearch-plugin install \
            file:///tmp/opensearch-late-interaction-1.0.0.0.zip
          
          # Restart OpenSearch to load the plugin
          docker restart opensearch
          
          # Wait for restart
          timeout 120 bash -c 'until curl -s -f http://localhost:9200/_cluster/health?wait_for_status=yellow; do sleep 2; done'

      - name: Verify plugin installation
        run: |
          # Verify plugin is installed
          docker exec opensearch /usr/share/opensearch/bin/opensearch-plugin list | grep "opensearch-late-interaction"
          
          # Verify cluster health after plugin installation
          curl -s http://localhost:9200/_cluster/health